version: "3.8"
services:
  web:
    platform: linux/arm64
    image: processmaker/pm4-core:${PM_VERSION}
    restart: unless-stopped
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_URL
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/code/pm4/storage
    links:
      - redis
      - mysql
    depends_on:
      - mysql
      - redis 
  redis:
    platform: linux/arm64
    image: redis
  mysql:
    platform: linux/arm64
    image: biarms/mysql:5.7.30
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
volumes:
  database:
  storage: